// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqDfAzfQcYbucpJ-LNWW6676bMZoJYXf4',
    appId: '1:638272735357:web:b4df497a0069dcc4a0c914',
    messagingSenderId: '638272735357',
    projectId: 'esp32-cam-c4527',
    authDomain: 'esp32-cam-c4527.firebaseapp.com',
    databaseURL: 'https://esp32-cam-c4527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-cam-c4527.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBvC25i6P9hRJ7LeK7tqdPVVaLrBf2jls',
    appId: '1:638272735357:android:99bf18dbea748ddda0c914',
    messagingSenderId: '638272735357',
    projectId: 'esp32-cam-c4527',
    databaseURL: 'https://esp32-cam-c4527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-cam-c4527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '638272735357',
    projectId: 'esp32-cam-c4527',
    databaseURL: 'https://esp32-cam-c4527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-cam-c4527.firebasestorage.app',
    iosBundleId: 'com.example.smartLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '638272735357',
    projectId: 'esp32-cam-c4527',
    databaseURL: 'https://esp32-cam-c4527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-cam-c4527.firebasestorage.app',
    iosBundleId: 'com.example.smartLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '638272735357',
    projectId: 'esp32-cam-c4527',
    authDomain: 'esp32-cam-c4527.firebaseapp.com',
    databaseURL: 'https://esp32-cam-c4527-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-cam-c4527.firebasestorage.app',
  );
}
